### ISSUE TITLE
NPM install error EINVALID:  tag contains characters that would normally be encoded by encodeUriComponent

### ISSUE THREAD

**Issue by ak37165** [zentered/solid-image-crop#17]
When installing using npm, the installation shows error: 

`npm error Invalid tag name "^>=1.6.0" of package "solid-js@^>=1.6.0": Tags may not have any characters that encodeURIComponent encodes`

**Comment by PatrickHeneise** [comment]
Thanks for raising the issue! Not sure where that `^` came from, but should be resolved in https://github.com/zentered/solid-image-crop/releases/tag/v1.1.1
